s = [
    "brand",
"Aardman Animations Limited et al",
"ABG-Champion LLC",
"ABG-Lucky, LLC",
"ABG-Volcom，LLC",
"Abraham",
"Abraham Hunter",
"Adidas",
"Adr Products LLC",
"Advance Magazine Publishers",
"Agata Wnuk",
"AJM Packaging Corp",
"Alastin Skincare",
"Albert Koetsier",
"ALBION BRAND FOUNDRY LTD",
"Albion Brand Foundry LTD",
"Alena Pavluchenko",
"Ali Gulec",
"Alison Friend",
"ALLSEASON ENTERPRISES, LLC",
"Allstar Marketing Group, LLC",
"Alo, LLC",
"Alona Savchuk",
"Along Ge",
"Alpha Signs and Designs",
"Amborui Electronic Tech. Co., Ltd.",
"American Honda Motor Co., Inc.",
"Amy Brown",
"Anagram International",
"Anderson Design Group, Inc.",
"Andrea Alice Muller",
"Andrew Blair Bailie",
"Andrew Dobell",
"Andrey Prokhorov",
"Angela Jean Talbert",
"Angelea Clark Van Dam",
"Anna Jdanova",
"Anna Melis",
"ANNEX PRODUCTS PTY. LTD.",
"Antsy Labs",
"AO 公司",
"Apple",
"Arnie Fisk",
"Art Ask Agency",
"Art Licensing",
"Atari Interactive",
"Atelier Eumori",
"August Image.LLC",
"Avenged Sevenfold",
"Ayaka Inoue",
"Baby Shark",
"Bala Bangles",
"Balazs Solti",
"Bang & Olufsen",
"Bang Bang Merchandise LLP",
"Barbara DiPietro",
"Baziuk Holdings",
"BBC Studios",
"BEADNOVA",
"Believe Pursue",
"Berluti SA",
"Bestway Inflatables & Material Corp.",
"Beth Hoselton-Gray",
"Better Mouse",
"Betty`s Best",
"Bev Doolittle",
"Beverly Salas",
"Big Potato Enterprises Limited",
"Billy Zebulon Norrby",
"Bin Liu",
"Binglin Zhong",
"Birkenstock",
"Birkir Eythor Asgeirsson",
"Blend Frend",
"Blend Frend",
"Blink Industries Ltd",
"Blujay Studios",
"BlushCrunch Studio",
"Boardriders",
"BOARDRIDERS IP HOLDINGS",
"Bob Ross, Inc.",
"Boris Afremov",
"Botanical Arts Press",
"Bounce Curl",
"Bravado International Group Merchandising Services",
"Brian Michael Allen",
"BRIGHT HEAD",
"Bring Me the Horizon (BMTH)",
"Britto Central",
"BRYAN FLETCHER and GARRETT FLETCHER",
"Bug Art Limited",
"Bulgari, S.p.A.",
"Bunch O Balloons",
"Burberry Limited",
"Caglayan Kaya Goksoy",
"Calvin Klein",
"Calvin Klein Trademark Tr",
"CamelBak",
"Cameron Gray",
"Canada Goose",
"Canrui Zhang",
"CAO Group, Inc",
"Capcom Co., Ltd.",
"Caraway Home, Inc.",
"Care Bears",
"Carolina Windmuller",
"Carrie Schmitt",
"Cartier International A.G.",
"Casio",
"CBS Studios, Inc.",
"Cecilia Granata",
"Celine",
"CELINE CORPORATION FRANCE",
"Ceremony of Roses Acquisition LLC",
"Chamese",
"Chanel",
"Changzhou Yichen Trading Co Ltd",
"Chapter 4 Corp.",
"Charlie Bowater",
"Cheech and Chong’s Global Holding Company",
"Chen Li",
"Chengliang Wang",
"Chenxi Zeng",
"Cherry Xtrfy AB",
"Chi Keung Lai",
"Choose Friendship LLC",
"Christian Dior Couture SA",
"Christian Velazquez",
"Christine Poppy Duffield",
"Christine Sharon Arnall",
"Chrome Cherry Design Stud",
"Chrome Hearts",
"Chubby Gorilla, Inc.",
"Chunqing Wang",
"CJ LTD",
"Clint Robert Padilla",
"Cole Haan",
"COLLEGIATE LICENSING COMPANY",
"Collegiate Licensing Company, LLC",
"Collin Bogle",
"Comefresh (Xiamen) Electronic Co. Ltd.",
"COMMON CENTS DISTRIBUTORS, LLC",
"Conan Doyle Estate Limited",
"Converse Inc.",
"Cosmoglo",
"COSRX",
"Courtney Morgenstern",
"Cozy Comfort Company LLC",
"Cranston Print Works Company",
"Crimpit Group Ltd.",
"CRISTA S. FOREST",
"Crye Precision",
"Crye Precision LLC",
"Crypton Future Media Inc",
"D Squared Plant Traps LLC (DSPT, LLC)",
"Daimler Truck Ag et al",
"Daniel Jay Eskridge",
"Daniel John Watts",
"Daniel Sundahl",
"Daria Novak",
"Darrell Bush",
"David Benito Perea Jr.",
"David Bryan Wentworth",
"David Lozeau",
"Dcstar, Inc.",
"Debra Coules",
"Deckers Outdoor Corporation",
"DEFTONES",
"Del Parson",
"Design Collection, Inc.",
"Desmond Noel Brophy",
"DH Eagles Ip LLC",
"Diane Kater",
"DiFOLD Inc.",
"Dimlight Forest 昏暗的森林",
"Dina Alexandrovna Earl",
"Dior 迪奥",
"Dispensing Technologies B.V.",
"DIVING MASK",
"DLE Tech",
"Dmitry Barkov",
"Dona Gelsinger",
"Dongguan Best Travel Electronics Co., Ltd.",
"Dongguan Fangde Network Technology Co., Ltd.",
"Dongguan Juyuan Precision",
"Dongguan Lianguang Electronics Technology Co., Ltd.",
"Dongguan Shuangjun Electronics Co., Ltd.",
"Dongguan Tesimai Electronic Technology Co.",
"Dongguan Yanrui Trading Co., Ltd",
"Dongguan Yanrui Trading Co., Ltd.",
"Dongshang Lin",
"Dongyu Zhang",
"Donice Bloodworth Jr.",
"Dorina Zieske",
"DORNA SPORTS, S.L.",
"Douglas Cavanaugh",
"DPG USA Inc.",
"Dreams USA, Inc.",
"DreamWorks Animation LLC",
"dresslily",
"Dropcases, LTD",
"Dropcases, Ltd.",
"DSSTAR INC",
"Dyson",
"Dyson Technology Limited",
"Eagles, Ltd.",
"Eduardo Andre Ely",
"EE HOLDING GROUP LLC",
"Eicher Motors Limited",
"Elaine Kay Maier",
"Electrasense Technologies, LLC",
"Elena Faenkova",
"Elena Kolotusha",
"E-Link Plastic & Metal Industrial Co., Ltd.",
"Elizabeth Anne Evans",
"Elizabeth Mazur",
"Ellen Lynn Negley",
"Emikeni Inc., f/k/a Straplets Inc.",
"EnchantedMob, Inc",
"EnchantedMob, Inc.",
"EnchantedMob, Inc. et al",
"Enduring Brand, LLC",
"Entertainment One UK Ltd.",
"Epic Games",
"Epicord",
"Epoch Company, Ltd",
"Erik Diedrichsen and Riverbend Resources Inc.",
"Esther Luntadila",
"Eva Gamaiun",
"Eva Gentcheva Campbell",
"Ex-Boyfriend, LLC dba Boredwalk",
"Fall Out Boy, Inc",
"Fanjiajia Jin",
"FCA US LLC",
"Fear of God, LLC",
"Federation of the Swiss Watch Industry FH",
"FEI CAO",
"Fender Musical Instruments Corporation",
"Fendi S.R.L.",
"Fendi, S.r.l.",
"Fengwei Shu",
"Fengxian Chendian Electronic Commerce Co., Ltd.",
"Finlay William John McGilp",
"Fleetwood Mac",
"Fleischer Studios, Inc",
"Fletcher et al",
"Floatsup, LLC",
"FlowBee Australia PTY LTD",
"Foreo Inc.",
"Fox Head, Inc.",
"FOX HEAD,INC",
"Franck Slama, an individual (艺名: Invader)",
"Frederator Networks, Inc.",
"FRIDA KAHLO CORPORATION",
"Fujian Mingta Toys Co. Ltd",
"FURminator",
"G59 Merchandising , INC.",
"Gag Gifts For Good Causes, LLC",
"General Motors LLC",
"Genie-S International Ltd.",
"George &amp; Company LLC",
"Georgia Janisse",
"GEORGII NIKOLAYEVICH DIACHENKO",
"Georgii Nikolayevich Diachenko",
"Gerrel Saunders",
"Gianni Versace S.r.l.",
"GIRO",
"GJL Holding Company LLC",
"Glitch Productions PTY LTD",
"Gloria West Kendall",
"Gold’s Gym",
"Goorin Bros. inc.",
"Grazyna Maniecka",
"Greg Giordano",
"Gregory Gorham",
"Greta Anthony",
"Griffin Waldau",
"Grill Scraper",
"GROUND WORKS",
"GROUND WORKS CO., LTD.",
"Grumpy Cat Limited",
"GS Holistic, LLC",
"Guangdongsheng Shunhechuanmei Co., Ltd.",
"GUANGZHOU LUCK COMMERCE CO.LTD.",
"Guanyi Zhang",
"Guanyu (Shenzhen) Electronic Technology Co., Ltd.",
"Gucci America, Inc.",
"Guizhou Xiaozhi Sheep",
"Gulan Liao",
"GuzzleTech",
"G型无线充电氛围灯",
"Hallmark",
"Hangzhou Yuanzu Technology Co., Ltd",
"Hannah Mae Rosengren",
"Hao Hu",
"Happy Bee Innovations",
"Hari Studios",
"Harlem Globetrotters International",
"HARLEY-DAVIDSON",
"Harry Styles",
"Hasbro Consumer Products",
"HB Feeder",
"Heather Myers",
"Heather Picquelle",
"Heatherlee Chan",
"Heng Swee Lim",
"Hexin Holding Limited",
"Honeyera, LLC",
"Hong Kong Leyuzhen Technology Co., LTD",
"Howard Raymond Green",
"Howard Robinson",
"Hozier",
"Hu Haolin",
"HUANGJI YANG",
"Hublot Sa",
"Ian",
"ICON WORLDWIDE PTY LTD",
"ICON Worldwide Pty LTD",
"Iconic NKC IP LLC",
"Igor Carver",
"Ina Tomecek",
"Ink & Rags LLC",
"In-N-Out Burgers",
"Innovatco",
"Intersel Ventures",
"Iron Maiden Holdings",
"Iuliia Gosteva",
"Ivaylo Nikolaev Nikolov",
"James Avery Craftsman, Inc.",
"James Booker",
"Jantz &amp; Jantz GbR d/b/a Anita's &amp; Bella's Art/\"Artwork\"",
"Jason Heuser",
"Jean Ann Plout",
"Jennifer Lambein",
"Jennifer Le Feuvre",
"Jennifer Lommers",
"Jennifer Megan Budrock",
"Jensen Tabangcura",
"Jeremiah David Morelli",
"Jessica Rose Hanselmann",
"Jetteo",
"Jiangchuan",
"Jin Li",
"Jody Lynn Bergsma",
"JOEL P. PRICE",
"John Fawcett Vogt",
"Jonas Brothers",
"Jonas Sebastian Jodicke",
"Jonna Hyttinen",
"Joseph Murray Hautman",
"Joshua Eugene Dail",
"Jrod",
"JTLE Investments",
"Juanren Wu",
"Juicy Couture",
"Julie Stiebritz",
"Jumali Bin Katani",
"Jun Fang",
"Junjiao Wei",
"Justine Osborne",
"KANG YANG",
"Kappa AgTech",
"Karsten Manufacturing Corporation",
"Kate Louise Powell",
"Katherine Elizabeth Kingston",
"Katherine Quinn",
"KAWS, INC.",
"KAYOMI HARAI",
"Kayomi Harai",
"Kelly Toys Holdings, LLC",
"Kelsey Dawn McNatt",
"Kendra Dandy",
"Kendra Scott",
"KHARA",
"KHARA INC",
"Khara Inc., Ground Works Co., Ltd.",
"Kim Haskins",
"Kitsch",
"Koninklijke Philips N.V.",
"Kristin Mastoras",
"Kristy Beth Patterson",
"KTM AG",
"Kuiper Ventures LLC",
"Kundian Guo",
"Kyndred Spirit, LLC",
"Lacoste Alligator S.A.",
"Laltitude LLC",
"Lando Norris",
"Laura Annette Zollar",
"Laura Graves",
"Lauren",
"LAURENE MEGER",
"Lawrence Hersberger",
"Leatherman Tool Group, Inc",
"LeChong Maoyi Xiantao Youxiangongsi",
"Leeza Hernandez dba Leezaworks LLC",
"Legend Pictures, LLC",
"Levi Strauss & Co.",
"LIFE VAC LLC",
"Lingyun Wang",
"Lisa Anne-Marie Parker",
"Lisa Audit",
"Little ELF Products.INC",
"Living Active, LLC",
"Liyu Liu",
"Longchamp",
"Lori Deiter",
"LOUIS POULSEN",
"Lovitedo",
"LOVITEDO, LLC",
"Lucia Heffernan",
"LUCIE BILODEAU",
"Lucio and Meera Santoro T/A Santoro Licensing",
"LUCKY",
"Lucky 13",
"Lucky Wang",
"Lululemon",
"LUXOTTICA GROUP S.p.A., and OAKLEY, INC",
"Luxury Brands LLC",
"LV",
"Lynyrd Skynyrd Productions, Inc.",
"Mac Miller",
"Madngine Inc.",
"Magnetic Bag Company",
"Makiko Kimura",
"MAKORS OU",
"MANCHESTER UNITED FOOTBALL CLUB LIMITED",
"MARATAC",
"Marcello Corti",
"Margarita Lypiridou",
"Maria Belyakova",
"Maria Belyakova (Marusha Belle)",
"Maria Hayden",
"Maria Isabel Alvarez Charro",
"Mariann Johansen-Ellis",
"Mario Sanchez Nevado",
"MARK GEMMELL",
"Mark Marko",
"Marshall Amplification PLC",
"Marta Rodriguez Veiga",
"Mary Elizabeth Hining",
"Mattel, Inc.",
"Maya Spielman",
"Megan Steiger",
"Melissa Bamberg",
"Merch Traffic",
"Merch Traffic, LLC",
"MERCIS B.V.",
"Messika Group",
"METALLICA",
"Metzfab Industries",
"MiaCharro",
"Michael Buxton",
"Michael Locascio",
"Michelle E. De Sousa&nbsp;Jose De Jesus De Sousa",
"Microjig",
"Microsoft Corporation",
"Mielle Organics, LLC",
"Miffy米菲兔",
"Millie Sewell-Knight",
"Millimages S.A.",
"Milwaukee Electric Tool Corporation",
"Minjae Lee",
"Miraculous Ladybug",
"Mob Entertainment, Inc",
"MOB ENTERTAINMENT, INC.",
"Mohamed Gad Elrabrez",
"Monster Energy Company",
"Motley Crue Inc.",
"Multipla Limited",
"Na Qui",
"Nanoblock",
"Naomi Claire Judd Tavares",
"NBA Properties, Inc.",
"NBC||Nbcuniversal Media, Llc",
"Neman Brothers &amp; Associates, Inc.",
"Netvue",
"NEWAGE SUPPLY, INC.",
"NewAge Supply, Inc.",
"NHL Enterprises, L.P.",
"Nicolette Rahner",
"Night Cap It LLC",
"NIKE, Inc.",
"Nike, Inc.",
"NINA MARIKA GRONLUND",
"Ningbo Langyan Agel E-commerce Ltd.",
"Nir Perelshtein",
"Nirvana, L.L.C",
"NISSAN",
"Not a Real Holding Company Inc",
"Oakley",
"Olga Drozdova",
"Olga Zikova",
"Olha Moroz",
"OLIVIER LE QUEINEC",
"On Clouds GmbH",
"ORLY FIDELMAN",
"OUAI",
"Outward Hound",
"Panic! at the Disco",
"Patent One LLC",
"Patrice Murciano",
"Paul Collins",
"Paula Alejandra Navarro",
"Paula Jean McHugh",
"Peak Design",
"PEANUTS WORLDWIDE LLC",
"Peanuts Worldwide LLC",
"Peixian JiYi Cat Trading Co. Ltd.",
"Peng Li",
"Pengfei Ren",
"Petgravity (hangzhou) Technology Co., Ltd",
"PICKULS GIZMO",
"PINK FLOYD (1987) LIMITED",
"Pit Viper, LLC",
"PIZZA PACK LLC",
"Playboy",
"Plim Plim",
"Pluginz Keychains",
"Pocketpair, Inc.",
"POM Group Inc",
"POM Group Inc.",
"Pool Punisher, LLC",
"Popilush",
"Popsockets",
"Potato Ventures",
"Prime 4 Seasonings",
"Prime 4 Seasonings",
"Princess Karibo",
"PUFFIN COOLERS, LLC",
"Pure Body Logistics, Inc",
"Purkey Enterprises, LLC",
"Purple Innovation, LLC",
"Pushpeel LLC",
"Qin Zheng",
"Qingdao Ecopure Filter Co., Ltd.",
"Qingtao Yu",
"QUANZHOU***LTD",
"Rachael Taylor",
"Rachel Neville",
"Ralph Burch",
"Randall Ian Mackey",
"Randall Mackey",
"Rarog j.d.o.o.",
"RAZER",
"REA.DEEMING BEAUTY, INC.",
"Rea.Deeming Beauty, Inc.",
"Rebecca Fielding",
"Rebekah Leigh Marshall",
"Red Bull GmbH",
"Renjie Wan",
"Richemont International",
"Ride-on Luaggage",
"River Light V, L.P.",
"ROBERT SMITH",
"Robert Wavra",
"Roberto Emilio Sanchez Pena",
"Roblox",
"Roger Hall",
"Roi Visual Co., Ltd.",
"Roku",
"ROKU INC.",
"Ronald Kuang",
"Rongzhen Xuan",
"Rotita",
"Rotita",
"Royal International, LLC",
"Royer Brands International S.A.R.L.",
"Rubie’s Costume Company",
"Rudi Hurzlmeier",
"Rumored Inc.",
"Run-Tiger LLC d/b/a Run Chicken",
"Ryan Conners",
"Ryan Conners/KilkennyCat Art",
"Ryford H. Estores",
"Ryze, Inc.",
"S.A.S. Jean Cassegrain and Longchamp USA, Inc.",
"Sabina Kulicka",
"Safeworld International",
"Sally Walsh",
"Sandra E. Kuck",
"Sandra Hutter",
"Sara Duarte",
"SASSAN FILSOOF",
"Sassan Filsoof",
"Sci Spark",
"Sebastian Burdon",
"Sega Corporation",
"SEGA CORPORATION and ATLUS CO., LTD",
"Sega Corporation and Atlus Co., Ltd.",
"SEMK Products Limited",
"Sen Zhang",
"Sesame Workshop",
"SHANGHAI XINQI ELECTRONIC TECHNOLOGY CO., LTD.",
"Shangxing Technology (Shenzhen) Co. Ltd.",
"SHANGYOU JIAYI LIGHTING PRODCUT CO., LTD.",
"Shangyou Jiayi Lighting Product Co., Ltd.",
"Sheena Lynn Pike",
"SheFit Operating Company, LLC",
"Shenzhen Aifasite Electronic Commerce Co., Ltd.",
"Shenzhen Anru Electronics Co., Ltd",
"Shenzhen Century Rainbow Ind. Co., Ltd.",
"Shenzhen Coolzon Development Co., Ltd, Huan Dai",
"Shenzhen HongHongJing Trading Co. Ltd.",
"SHENZHEN JISU TECHNOLOGY",
"Shenzhen Jisu Technology Co Ltd.",
"SHENZHEN JISU TECHNOLOGY CO., LTD",
"Shenzhen Jisu Technology Co., Ltd",
"Shenzhen Jisu Technology Co., Ltd.",
"Shenzhen Jugu Xingchen Technology Co., Ltd.",
"Shenzhen Kunshengze Elec-Tronic Commerce Co. Ltd.",
"Shenzhen Kunshengze Electronic Commerce Co., Ltd.",
"Shenzhen Lesheng Industrial Co., Ltd.",
"SHENZHEN MEIYUNLAI INTERNET CO",
"SHENZHEN PUJING SILICONE PRODUCTS CO., LTD",
"Shenzhen Quanxindi Technology Co. Ltd.",
"Shenzhen Saikenxin",
"Shenzhen Super Top Innovation Technology Limited",
"Shenzhen Xinchangtu Technology Co.Ltd.",
"SHENZHEN YIXUN TECHNOLOGY CO., LTD.",
"Shenzhen Zhitong Technology Co., Ltd.",
"Shenzhenshi Borunxing Wujin You Xian Gong Si",
"ShinStar",
"Shiwen Chen",
"Shortcake IP Holdings LLC",
"SHUANGXI ZHANG",
"Shuangxi Zhang",
"Shuxin Fu",
"Sig Sauer Inc.",
"simplehuman",
"Simply Mossy Art",
"SKECHERS U.S.A., INC. II",
"Skybrook E-Commerce, LLC",
"SmoothAir, Inc., d/b/a Form-A-Funnel, Inc.",
"Snactiv",
"Snyder Manufacturing,Inc.",
"Societe Pour L'OEUVRE et La Memoire D'ANTOINE De Saint \"Exupery - Succession De Saint EXUPERY-D'AGAY",
"SoClean, Inc.",
"Solawave Inc",
"Sony Interactive Entertainment LLC",
"Sophie Kirkpatrick",
"Sp5der",
"SpaceAid",
"SPIN MASTER LTD.",
"Spin Master Ltd. et al",
"Sport Dimension, Inc",
"Sport Dimension, Inc.",
"Stanislav Yurievich Osipov",
"Stanley",
"Steel City Enterprises, Inc.",
"Stefan Georgiev Petrunov",
"Sterling International Inc.",
"Steven Read",
"Steven Rhodes",
"Stewart Creative, Llc",
"Stojo Products Inc.",
"Striphair",
"Studio品牌",
"SUGARTOWN WORLDWIDE LLC",
"Sungwon Hwang",
"Sunniva Grotle Myster",
"Supercell Oy",
"Superhype Tapes, Ltd.",
"Supreme",
"Susan Catherine Holak",
"Susan Winget",
"Svenja Schmitt",
"Swarovski",
"Taku Shibata",
"Talon Tools, LLC",
"Tang Technology Co., Limited, Junzhou Huang",
"Tangle Inc.",
"Tanya Paget",
"Tatsiana Pilipenka",
"Taylor Bates",
"Taylor Made Golf Company, Inc.",
"Telebrands Corp.",
"Teleties, LLC",
"Terry Fan",
"Tetris Holding, LLC",
"THE AL AGNEW COLLECTION LLC",
"The Cure",
"The Elf on the Shelf圣诞精灵",
"The Estate of Marilyn Monroe, LLC",
"THE KRAK’IN",
"The Kyjen Company, LLC",
"The Liverpool Football Club and Athletic Grounds ,Limited"
"The Pencil Grip, Inc.",
"THE SMILEY COMPANY SPRL",
"The Smiley Company SPRL",
"THE UNIVERSITY ATHLETIC ASSOCIATION, INC.",
"THE WHISKEY GINGER, LLC",
"Theodora Ioana Magerand",
"Theodoros Zirinis",
"Thiago Mellado",
"Thomas Conrad Wood",
"Thomas Fedro",
"THOMAS WOOD",
"THOSE CHARACTERS FROM CLEVELAND",
"Thousand Oaks Barrel Co. LLC",
"Thrasio Twenty Two, Inc.",
"Tianjin shunxiang technology co., ltd",
"TIFFANY (NJ) LLC",
"Tiffany (NJ) LLC",
"Tiger Aspect Kids Family Limited",
"Timothy Adam Matthews",
"TinyBiotics",
"TOBIAS TEIXEIRA DA FONSECA",
"Tobias Teixeira Da Fonseca",
"Toho Co., Ltd.",
"TOLIFE TECHNOLOGIES PTY LTD and MOSHE MAOR",
"Tommy Hilfiger",
"Tongxiang Simai Trading Co., Ltd.",
"Tory Burch",
"Toyota Motor Sales, U.S.A., Inc.",
"Triumph Designs, Ltd.",
"Triumph International, LLC",
"TROVE BRANDS LLC、RUNWAY BLUE LLC",
"TV Tokyo Corporation",
"Ubisoft Entertainment, S.A. and Ubisoft",
"UGG",
"Ultra Pro International, LLC",
"United States Olympic and Paralympic Committee",
"Universal City Studios LLC",
"UNIVERSITY OF GEORGIA ATHLETIC ASSOCIATION, INC",
"US HEALTH DRUGSTORE INC.",
"Valeriya Valerievna Korenkova",
"Vasyl Duda",
"Vehicle Gap Guard",
"Vesna Delevska",
"Viacom International Inc.",
"Viacom International Inc.和Paws, Inc.",
"Victoria’s Secret & Co.",
"Vincent Hie",
"Vipanee Singsutee",
"Vista Outdoor",
"Volkswagen Group of America, Inc.",
"VOLOOM",
"WaggyDogz",
"WARNER BROS. ENTERTAINMENT INC",
"Warner Bros. Entertainment Inc.",
"Weezer",
"Weihong Ma",
"WEIQUAN ZOU",
"Weirdwatercolours Ltd.",
"Wenjie Xie",
"Whaleco Inc.",
"Wham-O",
"WILDMAN DRINKING COMPANY AND WILDMAN DRINKING LAB. LLC",
"Winnie Rosaline Kan",
"Winona Irene",
"Wmdc and WML, LLC",
"Woodpeckers, LLC",
"XAVORK WOOLIAND INC.",
"Xiangxin Liu",
"Xiaogang Pang",
"XIAOMI",
"Xiaoyan Qian",
"Xingshao Li",
"Xiong Li",
"Xuanjun Cai",
"Xueyuan Chen",
"Yasushi Matsuoka",
"Yazel Media LLC",
"YC",
"Yee San Loh",
"YETI COOLERS, LLC",
"YIPU (TIANJIN) INTELLIGENT TECHNOLOGY CO., LTD",
"Yipu (Tianjin) Intelligent Technology Co., Ltd",
"YIPU（TIANJIN）INTELLIGENT TECHNOLOGY CO.，LTD",
"Yiwu Baimei Electronic Commerce Co., Ltd.",
"Yiwu Langxun Electronic Commerce Co., LTD",
"Yiwu Mode E-Commerce Co., Ltd.",
"Yoeu Inc",
"Yongxiang Chan",
"YSN Imports LLC dba Flame King",
"ysn imports llc dba flame king",
"Yu Chen",
"Yun Kyung Lee",
"Yuxiang Chen",
"Zemiao Chen",
"Zhihua Wu",
"Zhiwei Wu",
"ZHIYONG Huang",
"Zhongwei Qiu",
"Zhuhai Shengchang Electric Co., Ltd.",
"Zorro Productions, Inc.",
"憨豆先生 MR BEAN",
"激光校准器",
"哪吒",
"森林蜗牛蘑菇",
"世嘉 Sega Corporation",
"托特纳姆热刺足球俱乐部 Tottenham Hotspur Limited",
"托托特纳姆热刺足球俱乐部 THFC",
"未知（儿童名牌商标）",
"亚马逊",
]

# 找出 s 的重复值
from collections import Counter
counts = Counter(s)
duplicates = [x for x, c in counts.items() if c > 1]
print("重复值个数:", len(duplicates))
print("重复值列表:")
for x in duplicates:
    print(f"  {repr(x)} (出现 {counts[x]} 次)")